# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
  workflow_dispatch:

jobs:
  build:

    runs-on: development

    strategy:
      matrix:
        node-version: [17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: |
        touch .env
        echo REACT_APP_DOMAIN = ${{ secrets.REACT_APP_DOMAIN_TEST }} >> .env
        echo REACT_APP_SERVER_DOMAIN = ${{ secrets.REACT_APP_SERVER_DOMAIN_TEST }} >> .env
        echo REACT_APP_AUTH0_DOMAIN = ${{ secrets.REACT_APP_AUTH0_DOMAIN_TEST }} >> .env
        echo REACT_APP_AUTH0_CLIENT_ID = ${{ secrets.REACT_APP_AUTH0_CLIENT_ID_TEST }} >> .env
        echo REACT_APP_AUTH0_AUDIENCE = ${{ secrets.REACT_APP_AUTH0_AUDIENCE_TEST }} >> .env
        echo REACT_APP_SERVER_URL = ${{ secrets.REACT_APP_SERVER_URL_TEST }} >> .env
        echo REACT_APP_AUTH0_LUMEN_AUDIENCE = ${{ secrets.REACT_APP_AUTH0_LUMEN_AUDIENCE_TEST }} >> .env
        cat .env
    - run: CI='' npm run build --if-present
    - run: rsync -a /actions-runner/frontend/_work/saber-socialmedia-portal-frontend/saber-socialmedia-portal-frontend/build/ /var/www/frontend/
